### PR TITLE
AO-27:Reduce Travis Build Time

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/AO-27
cc @dkayiwa  @ibacher

### CODE REVIEW

**Comment by sherrif10** [comment]
Travis now can build in less than 30 seconds which has eased the work cc @dkayiwa

**Comment by dkayiwa** [comment]
@sherrif10 increase or reduce?

**Comment by sherrif10** [comment]
sure its reduce travis build

**Comment by dkayiwa** [comment]
Do you mind explaining how these changes reduce the travis build time?

**Comment by sherrif10** [comment]
So ideally file named **travis_wait "n"** is the function that exports the build functionality , then the prefix n is the number of minutes by which the waiting time is extended. travis_wait works by starting a process of building the project, sending it to the background, and watching the background process.

**Comment by sherrif10** [comment]
cc @dkayiwa , any suggestion on this is it worth it

**Comment by dkayiwa** [comment]
@sherrif10 closing this because we are moving away from travis.

**Pull request closed without merging**
