### PR TITLE
Update the release of System Administration OWA

### PR DESCRIPTION
**Pull request by suthagar23**
Please find the related [here](information https://bintray.com/suthagar23/owa/openmrs-owa-sysadmin) and [here](https://talk.openmrs.org/t/system-administration-open-web-app-v1-0-released/13141) to merge this changes

### CODE REVIEW

**Comment by dkayiwa** [comment]
@reubenvarghese1 do you approve this? 😊

**Comment by dkayiwa** [comment]
@suthagar23 can you look into these merge conflicts?

**Comment by reubenvarghese1** [comment]
@suthagar23 @dkayiwa    The PR looks good to me . @suthagar23 , you just need to pull the latest changes locally and then update this PR. Also is there any reason due to which you added that comma at line 4073?

**Comment by djazayeri** [comment]
1. The merge conflicts are probably because there was another PR (to add the Cohort Builder) that was merged after you created yours. So, yes, you just need to pull+merge+update the PR.

2. That comma at the end would break things. Gotta fix that.

(@reubenvarghese1, let's get travis set up so this would be caught automatically)

**Comment by reubenvarghese1** [comment]
Closing and reopening this PR to check if it is detected by travis

**Comment by reubenvarghese1** [comment]
I missed the fact that this PR has a merge conflict. Maybe that's the reason why travis isn't detecting this PR

**Comment by suthagar23** [comment]
I will close this PR to create another PR with updated changes with issue ID. Please find https://github.com/openmrs/openmrs-contrib-addonindex/pull/26

**Pull request closed without merging**
