### PR TITLE
[GCI-179] Add relevant tags to OpenMRS AddOns modules

### PR DESCRIPTION
**Pull request by tomekdo3**
### Issue: 
https://issues.openmrs.org/browse/GCI-179
#### I've added "statistics" tag for statistic related addons and "patient-management" tag for patient related addons. Plus I've added "search" tag for File Browser addon

### CODE REVIEW

**Comment by reubenvarghese1** [comment]
I feel the patient management is quite redundant as OpenMRS is mostly about patient management! Try thinking of other tags :)

**Comment by tomekdo3** [comment]
@reubenvarghese1 I've removed "patient-management" and added new "registration" tag. What do you think about that one? :)

**Comment by tomekdo3** [comment]
Hi @djazayeri I've followed your instructions :)

**Comment by reubenvarghese1** [comment]
@tomekdo3 Good job, thanks!

**Pull request merged**
