### PR TITLE
AO-20: Created a list of RefApp 2.8 modules

### PR DESCRIPTION
**Pull request by anuar2k**
## Description of what I changed
I've added a list of RefApp 2.8 modules to the addons index. I've also fixed a couple of typos in the file structure.

## Issue I worked on
see https://issues.openmrs.org/browse/AO-20

Link to the task instance:
https://codein.withgoogle.com/dashboard/task-instances/6142415594323968/

## Notes
I have used this wiki page as the source for the list:
https://wiki.openmrs.org/display/RES/Release+Notes+2.8.0

**I did not list UI Test Framework 2.2.0, as it is not available on https://om.rs/addons**

### CODE REVIEW

**Comment by reubenvarghese1** [comment]
@djazayeri What do you think?

**Comment by dkayiwa** [comment]
@reubenvarghese1 can you merge this?

**Comment by dkayiwa** [comment]
@reubenvarghese1 ping

**Comment by dkayiwa** [comment]
@reubenvarghese1 feel free to revert if you are not happy with this. 😊

**Comment by reubenvarghese1** [comment]
@dkayiwa , so sorry for having missed this. Thanks for the initiative :-)

**Pull request merged**
