### PR TITLE
Revert "Revert "AO-26A:Create A List of RefApp 2.11 modules only for openmrs AddonIndex""

### PR DESCRIPTION
**Pull request by dkayiwa**
Reverts openmrs/openmrs-contrib-addonindex#88

### CODE REVIEW

**Comment by dkayiwa** [comment]
@sherrif10 i had merged [the other one](https://github.com/openmrs/openmrs-contrib-addonindex/pull/87) accidentally. So replace it with this.

**Comment by dkayiwa** [comment]
@sherrif10 is there any reason why you are editing the 2.10.0 list instead creating a new one for 2.11.0

**Comment by sherrif10** [comment]
Sorry for late reply @dkayiwa , i think we needed to write two pr for both refApp2.10 and refApp 2.11 as i did

**Comment by sherrif10** [comment]
Seems i cant close it but let me open up a clean ticket thanks

**Pull request closed without merging**
