### PR TITLE
Added RefApp 2.7 Module version List to add-ons-to-index File

### PR DESCRIPTION
**Pull request by tendomatGitHub**
@djazayeri  Can you please look at the validity of this ?
cc.@dkayiwa
continuation of  https://talk.openmrs.org/t/updating-add-on-index-lists-with-new-reference-application-releases/14984/14

### CODE REVIEW

**Comment by reubenvarghese1** [comment]
@tendomatGitHub I noticed that you have added a new section for Ref app 2.7 instead of updating the Ref app 2.6 section( https://github.com/tendomatGitHub/openmrs-contrib-addonindex/blob/4c905d8be082668423314d371b0f2cbf08159980/src/main/resources/add-ons-to-index.json#L4556 ). Kindly do that and thanks for your PR :)

**Comment by tendomatGitHub** [comment]
@reubenvarghese1 thanks for revieiwing,however @djazayeri had directed me to do that. as per https://talk.openmrs.org/t/updating-add-on-index-lists-with-new-reference-application-releases/14984/14

could there  be something wrong with that?

**Comment by tendomatGitHub** [comment]
@reubenvarghese1  Thanks for reviewing this.I however did so in accordance with what @djazayeri  told me at https://talk.openmrs.org/t/updating-add-on-index-lists-with-new-reference-application-releases/14984/14

could that cause problems to the over all workflow of then index?

**Comment by reubenvarghese1** [comment]
@tendomatGitHub Sorry for the misinformation. I can see that Darius has asked you to that 👍

**Comment by tendomatGitHub** [comment]
@reubenvarghese1  ha ha no worries bro.But thanks also for reviewing my work.I appreciate that alot.

**Comment by djazayeri** [comment]
Looks good to me, I will merge it and check it out on the staging server.

@reubenvarghese1 the idea is that we'd maintain addon lists for all the past refapp releases. (They'll disappear behind a "see more" link so it won't clutter things up front.)

**Comment by djazayeri** [comment]
(Oops, I see that there's somehow a src/main/resources/add-ons-to-index.json~ file there, which is a mistake, so I will do a followup commit to delete this.)

**Comment by reubenvarghese1** [comment]
Ah, I see, so it's a feature that we are yet to incorporate into Add-ons

**Comment by tendomatGitHub** [comment]
Thanks alot Darius

**Comment by tendomatGitHub** [comment]
@djazayeri I actually saw that during pushing,but was not sure of the cause.I think I need to do some house cleaning of my local environment, it's doing weird things lately.

**Pull request merged**
