### PR TITLE
AO-18: Add source and documentation links to each module.

### PR DESCRIPTION
**Pull request by Symt**
I was having trouble claiming the issue ([https://issues.openmrs.org/projects/AO/issues/AO-18?filter=allopenissues](issue)) so I just did it without taking it (Sorry). The blank links ("href":"") were places where I couldn't find the documentation/source after extensive research.

(for gci)

### CODE REVIEW

**Comment by Symt** [comment]
@reubenvarghese1 Should a title be added for the sources and the documentation, or just the documentation?

**Comment by Symt** [comment]
@reubenvarghese1 I pushed and squashed the commits with the updates. However, there was still one repo that had no documentation or github readme (I believe I left the link empty).

**Comment by reubenvarghese1** [comment]
@Symt  I just checked with @djazayeri regarding this and he recommends that you omit that particular field altogether when something is missing. For example: If there isn't a link for a module's documentation available, do not have the section altogether but do include the link to the source if that's available.

**Comment by Symt** [comment]
@reubenvarghese1 If neither is present, remove the links altogether?

**Comment by therealestkevin** [comment]
Uhhhhh... I think you couldn't claim it because I was working on it. Should I still submit a PR because I essentially did the same work as Symt but I claimed the task before so I think that is why he ran into a claiming problem.

**Comment by therealestkevin** [comment]
@Symt You might want to check on JIRA next time to see if someone has claimed a task before working on it.

**Comment by dkayiwa** [comment]
@reubenvarghese1 do you wanna merge this?

**Comment by reubenvarghese1** [comment]
@dkayiwa , I have been testing this PR locally. I did so yesterday and for some reason, these changes were not producing the output expected. Although, I am pretty certain that this PR is good, as long as I do not debug the problem locally, I do not want to merge it. Would that be fine or do you suggest I merge it anyway(I can test the other PRs in the meantime)?

**Comment by dkayiwa** [comment]
In that case, i would trust your judgement not to merge this for now 👍

**Comment by dkayiwa** [comment]
@reubenvarghese1 did you get a chance to make any progress on this? 😊

**Comment by reubenvarghese1** [comment]
Thanks @Symt . @dkayiwa , we have decided to merge the pr since I don't think there's an issue with the pr. The feature not working has to do with our codebase which needs to be looked into. Thanks for your reminders :)

**Pull request merged**
