### PR TITLE
OpenHMIS Inventory release 2.4.1

### PR DESCRIPTION
**Pull request by andrewmoko**

### CODE REVIEW

**Comment by reubenvarghese1** [comment]
@andrewmoko Can you please check your code? Something is making it fail.

**Comment by reubenvarghese1** [comment]
Actually no, I just looked at the code. Looks like you have placed it in the wrong position. Try placing it after [this](https://github.com/andrewmoko/openmrs-contrib-addonindex/blob/a094b89c99917807dea9b7781707e8a4a3781056/src/main/resources/add-ons-to-index.json#L2268).

**Comment by andrewmoko** [comment]
Actually the module I'm trying to add is already there https://github.com/andrewmoko/openmrs-contrib-addonindex/blob/a094b89c99917807dea9b7781707e8a4a3781056/src/main/resources/add-ons-to-index.json#L3591. I'll close this PR.

Question: How are we supposed to release new stuff? I think I'm unclear on the matter. We used to go to modules.openmrs.org and upload the module. How should we do it now? Thanks

**Comment by reubenvarghese1** [comment]
@andrewmoko You may want check [this](https://addons.openmrs.org/#/about) out for further details regarding what you wish to accomplish. If you have any further questions, feel free to create a post on talk and I'll address it :)

**Comment by andrewmoko** [comment]
Thanks. I'm now clear!

**Comment by djazayeri** [comment]
Reuben, maybe we should update the About page to specifically say that we
will automatically find your newly-released versions after you publish them
(but this may be delayed by a few hours).

**Comment by reubenvarghese1** [comment]
True, I'll add that change in the next PR

**Pull request closed without merging**
